<?php

/**
 * Dev-only: creates and fills the Atlas "About" page per Figma 339-3624.
 * Composition: banner hero, science split w/ floating cards, how-it-works,
 * dark physicians, package + product sliders, FAQ, final CTA, comparison,
 * testimonials — reused sections copy their data from the home page (run
 * atlas-home-fill.php first), variant sections apply overrides on top.
 * Run from the backend repo:
 * php artisan tinker /var/www/html/atlas-protocol-web/scripts/atlas-about-fill.php
 * IMPORTANT: afterwards run `php artisan cms:backfill-section-media`.
 * Content lives in this deployment's DB — intentionally NOT in any seeder.
 */

use App\Enums\PageStatus;
use App\Models\Page;
use App\Services\Cms\SectionRegistry;

$page = Page::firstOrCreate(
    ['slug' => 'about'],
    ['title' => 'About', 'status' => PageStatus::Published],
);

$page->update([
    'status' => PageStatus::Published,
    'title_banner' => ['enabled' => false],
    'meta_title' => 'About',
    'meta_description' => "Every protocol we issue is built and approved by a licensed physician — not generated by an algorithm. Here's who's behind it.",
]);

$home = Page::where('slug', 'home')->first();
$homeData = function (string $type) use ($home): array {
    $data = $home?->sections()->where('type', $type)->value('data');

    return is_array($data) ? $data : [];
};

$order = [
    'hero',
    'image-text-split',
    'how-it-works',
    'physicians',
    'package-slider',
    'product-slider',
    'faq',
    'final-cta',
    'comparison-table',
    'testimonials',
];

$registry = app(SectionRegistry::class);

foreach ($order as $i => $type) {
    $section = $page->sections()->firstOrCreate(
        ['type' => $type],
        ['enabled' => true, 'data' => $registry->resolve($type)->defaults()],
    );
    $section->update(['position' => $i + 1, 'enabled' => true]);
}

$disabled = $page->sections()->whereNotIn('type', $order)->update(['enabled' => false]);
if ($disabled > 0) {
    echo "disabled {$disabled} out-of-composition section(s)\n";
}

// Variant sections author their own data; reused sections copy home's.
$content = [
    'hero' => [
        'layout' => 'banner',
        'slides' => [],
        'eyebrow' => 'About Atlas Protocol',
        'headline' => 'Physician-led, by design',
        'subhead' => "Every protocol we issue is built and approved by Dr. Holland — not generated by an algorithm. Here's who's behind it, and why we built Atlas Protocol this way.",
        'primary_cta_label' => 'Start Your Wellness Journey',
        'primary_cta_url' => '#get-started',
        'background_image' => 'sections/main-hero-image-1a.png',
    ],
    'image-text-split' => array_merge($homeData('image-text-split'), [
        'float_cards' => [
            [
                'position' => 'top-right',
                'icon' => null,
                'value' => null,
                'text' => 'Designed by Leading Physicians',
                'rating_value' => 4.9,
                'rating_text' => '4.9/5 · 200+ reviews',
            ],
            [
                'position' => 'bottom-left',
                'icon' => null,
                'value' => '15+',
                'text' => 'years clinical practice',
                'rating_value' => null,
                'rating_text' => null,
            ],
        ],
    ]),
    'how-it-works' => $homeData('how-it-works'),
    'physicians' => array_merge($homeData('physicians'), ['theme' => 'dark']),
    'package-slider' => $homeData('package-slider'),
    'product-slider' => $homeData('product-slider'),
    'faq' => $homeData('faq'),
    'final-cta' => $homeData('final-cta'),
    'comparison-table' => $homeData('comparison-table'),
    'testimonials' => $homeData('testimonials'),
];

foreach ($content as $type => $data) {
    if ($data === []) {
        echo "SKIPPED (no home data to copy): {$type}\n";

        continue;
    }

    $section = $page->sections()->where('type', $type)->first();

    if ($section === null) {
        echo "MISSING section type: {$type}\n";

        continue;
    }

    $section->update(['data' => array_merge($section->data ?? [], $data)]);
    echo "filled: {$type}\n";
}

echo "done — now run: php artisan cms:backfill-section-media\n";
