<?php

/**
 * Dev-only: creates and fills the Atlas "How It Works" page per Figma
 * 337-1181 (page header banner, timeline, tinted image-callout banner,
 * FAQ, final CTA). Run from the backend repo:
 * php artisan tinker /var/www/html/atlas-protocol-web/scripts/atlas-how-it-works-fill.php
 * Images must exist in backend storage/app/public/sections/.
 * IMPORTANT: afterwards run `php artisan cms:backfill-section-media` — this
 * script writes legacy path strings (including title_banner.background_image),
 * and the admin's image picker wipes any it can't hydrate on the next save;
 * the backfill converts them to curator media ids first.
 * Content lives in this deployment's DB — intentionally NOT in any seeder.
 */

use App\Enums\PageStatus;
use App\Models\Page;
use App\Services\Cms\SectionRegistry;

$page = Page::firstOrCreate(
    ['slug' => 'how-it-works'],
    ['title' => 'How It Works', 'status' => PageStatus::Published],
);

$page->update([
    'status' => PageStatus::Published,
    'title_banner' => [
        'enabled' => true,
        'title_override' => null,
        'subtitle' => null,
        'intro_text' => null,
        'show_breadcrumbs' => true,
        'background_image' => 'sections/main-hero-image-1a.png',
    ],
    'meta_title' => 'How It Works',
    'meta_description' => 'Three steps, each reviewed by a licensed physician: take the health questionnaire, get your custom protocol, receive your peptide pens.',
]);

$order = ['timeline', 'image-callout-banner', 'faq', 'final-cta'];

$registry = app(SectionRegistry::class);

foreach ($order as $i => $type) {
    $section = $page->sections()->firstOrCreate(
        ['type' => $type],
        ['enabled' => true, 'data' => $registry->resolve($type)->defaults()],
    );
    $section->update(['position' => $i + 1, 'enabled' => true]);
}

// Scaffold sections from earlier seeds that aren't part of this composition
// (e.g. a bare text-block) would render as placeholders — switch them off.
$disabled = $page->sections()->whereNotIn('type', $order)->update(['enabled' => false]);
if ($disabled > 0) {
    echo "disabled {$disabled} out-of-composition section(s)\n";
}

$content = [
    'timeline' => [
        'heading' => 'From intake form to your door',
        'lead' => "Three steps, each reviewed by a licensed physician, not an algorithm. Here's exactly what happens at every stage.",
        'mark_image' => null,
        'steps' => [
            [
                'title' => 'Take the health questionnaire',
                'meta' => 'Takes about 8 minutes',
                'body' => 'A confidential online intake form covering your health history, current medications, goals, and any conditions relevant to peptide therapy. Done entirely from your phone or computer — no office visit required at this stage.',
                'bullets' => [
                    ['text' => 'Medical history, current medications, and allergies'],
                    ['text' => 'Your goals, weight, energy, recovery, or hormonal balance'],
                    ['text' => 'Basic measurements to help determine eligibility'],
                ],
            ],
            [
                'title' => 'Dr. Holland reviews and builds your protocol',
                'meta' => 'Typically 24-48 hours',
                'body' => "Your intake form goes directly to Dr. Holland's clinical team. Depending on your state, a synchronous video visit may be required. Your stack is hand-selected — not generated by an algorithm — based on your biology, goals, and medical history.",
                'bullets' => [
                    ['text' => 'Clinical review of your intake form by a licensed provider'],
                    ['text' => "A video visit if required by your state's regulations"],
                    ['text' => 'A custom protocol built and approved by Dr. Holland'],
                ],
            ],
            [
                'title' => 'You receive your peptide pens',
                'meta' => '2-5 business days',
                'body' => 'Once approved, your medication ships from an accredited compounding pharmacy in discreet, temperature-controlled packaging. Each box includes your peptide pens, supplies, and a personalized protocol guide.',
                'bullets' => [
                    ['text' => 'Peptide pens pre-filled and ready to use'],
                    ['text' => 'Syringes, alcohol pads, and storage instructions'],
                    ['text' => 'A written guide matched to your specific protocol'],
                ],
            ],
        ],
    ],
    'image-callout-banner' => [
        'background_image' => 'sections/angel-pen.png',
        'background_alt' => 'Peptide pen on a neutral background',
        'background_treatment' => 'tint',
        'tint_color' => '#f0e6da',
        'callouts' => [
            [
                'position' => '0',
                'variant' => 'media-card',
                'align' => 'top',
                'color' => null,
                'icon' => 'sections/atlas-pen.png',
                'icon_width' => 184,
                'title' => null,
                'content' => 'Peptide pens pre-loaded for your specific protocol',
                'cta_mode' => 'link',
                'cta_label' => null,
                'cta_url' => null,
            ],
            [
                'position' => '1',
                'variant' => 'feature',
                'align' => 'center',
                'color' => null,
                'icon' => null,
                'title' => "Everything you need, nothing you don't",
                'content' => "Your first shipment arrives with more than medication — it includes everything required to start your protocol confidently and safely, guided by Dr. Holland's clinical team for as long as you need support.",
                'cta_mode' => 'link',
                'cta_label' => 'Start My Program',
                'cta_url' => '#get-started',
            ],
        ],
    ],
    'faq' => [
        'heading' => 'Learn More About Our Programs',
        'description' => 'A physician-led telehealth platform connecting patients with licensed healthcare providers for personalized GLP-1 weight loss programs.',
        'cta_label' => 'More Questions',
        'cta_url' => '/faqs',
        'image' => 'sections/atlas-pen.png',
        'image_alt' => 'Atlas Protocol peptide pen',
        'faqs' => [
            [
                'q' => 'What Are GLP-1 medications?',
                'a' => "GLP-1 medications are prescription drugs that improve blood sugar control and support weight loss. They work by mimicking the glucagon-like peptide-1 hormone, which regulates appetite and insulin response. Common side effects include nausea, vomiting, and diarrhea — typically managed through careful dosage titration under Dr. Holland's guidance.",
            ],
            [
                'q' => 'How to take GLP-1 medication?',
                'a' => 'Your protocol guide includes step-by-step instructions matched to your prescription. Most GLP-1 medications are taken as a once-weekly injection with pre-filled pens designed for at-home use.',
            ],
            [
                'q' => 'What should I do if I miss a dosage?',
                'a' => 'If you miss a dose, follow the guidance in your protocol guide or message your care team. In most cases you can take the missed dose within a few days; never double up without clinical direction.',
            ],
            [
                'q' => 'How should I store GLP-1 medications?',
                'a' => 'Store your pens refrigerated per the label instructions. Each shipment arrives in temperature-controlled packaging with storage directions for your specific medication.',
            ],
        ],
    ],
    'final-cta' => [
        'eyebrow' => 'The Longevity Platform',
        'heading' => 'Your wellness journey starts here',
        'primary_cta_label' => 'Start my program',
        'primary_cta_url' => '#get-started',
    ],
];

foreach ($content as $type => $data) {
    $section = $page->sections()->where('type', $type)->first();

    if ($section === null) {
        echo "MISSING section type: {$type}\n";

        continue;
    }

    $section->update(['data' => array_merge($section->data ?? [], $data)]);
    echo "filled: {$type}\n";
}

echo "done — now run: php artisan cms:backfill-section-media\n";
